### get a default banner

GET   http://localhost:8080/banners/default
content-type: application/json 

### add a default banner

POST   http://localhost:8080/banners/default
content-type: application/json

{
    "image": "https://firebasestorage.googleapis.com/v0/b/minishop-b3604.appspot.com/o/banner%2Fbanner.webp?alt=media&token=680dab34-a734-4003-b038-5306a79e6961",
    "buttonText": "test",
    "desc": "test",
    "smallText": "test",
    "middleText": "test",
    "largeText1": "test",
    "largeText2": "test",
    "discount": "10%",
    "saleTime": "2021/12/01"
}