### get customers

GET   http://localhost:8080/customers
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOlsyMDAxXX0sImlhdCI6MTY1NTkwODk1NCwiZXhwIjoxNjU1OTA4OTY0fQ.ssRkn8xMgXjWElw2xeYQjVx6lFuesYwre9BFCQ8YFG4

### get a customer

GET   http://localhost:8080/customers/63451f6e20a4574c05311d6f
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOlsyMDAxXX0sImlhdCI6MTY1NTkwODk1NCwiZXhwIjoxNjU1OTA4OTY0fQ.ssRkn8xMgXjWElw2xeYQjVx6lFuesYwre9BFCQ8YFG4


### add a customer

POST   http://localhost:8080/customers
content-type: application/json

{
    "username": "lngocan1996",
    "email": "lngocan1996@gmail.com",
    "password": "11111111",
    "imgProfile": "https://firebasestorage.googleapis.com/v0/b/minishop-b3604.appspot.com/o/avatar.jpg?alt=media&token=34804fd3-dcdf-4c38-abb1-fd36fc7132b0",
    "country":  "Viet Nam",
    "joinDate": "2021/12/01",
    "lastAccessAt": "2021/12/01",
    "totalBill": 3000
}    


### add a customer

POST   http://localhost:8080/customers
content-type: application/json

{
    "username": "Nirav Joshi 7",
    "email": "nirav7@gmail.com",
    "password": "11111111"
}    


### update a customer

PUT    http://localhost:8080/customers/633e856e40dbbf039f2bf4b1
content-type: application/json

{
    "_id": "633e856e40dbbf039f2bf4b1",
    "username": "Nirav Joshi 7",
    "email": "nirav7@gmail.com",
    "password": "11111111",
    "imgProfile": "https://firebasestorage.googleapis.com/v0/b/minishop-b3604.appspot.com/o/avatar.jpg?alt=media&token=34804fd3-dcdf-4c38-abb1-fd36fc7132b0",
    "country":  "Viet Nam",
    "joinDate": "2021/12/01",
    "lastAccessAt": "2021/12/01",
    "totalBill": 3000,
    "birthday": "2000-11-30T17:00:00.000Z",
    "phone": "0901234567",
    "gender" : "men"
}   

### update a customer

PUT    http://localhost:8080/customers/63451f6e20a4574c05311d6f
content-type: application/json

{
    "_id": "63451f6e20a4574c05311d6f",
    "username": "lngocan1996",
    "email": "lngocan1996@gmail.com",
    "totalBill": 122
}  

### update a customer with 

PUT    http://localhost:8080/customers/633ea26ba02acc69764a430a
content-type: application/json

{
    "_id": "633ea26ba02acc69764a430a",
    "username": "test12344",
    "email": "test1234@gmail.com",
    "country":  "Viet Nam",
    "birthday": "2000-11-30T17:00:00.000Z",
    "gender" : "woman"
}

### delete a customer

DELETE    http://localhost:8080/customers/633e490ed0aa223dd791ff64
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOlsyMDAxXX0sImlhdCI6MTY1NTkwODk1NCwiZXhwIjoxNjU1OTA4OTY0fQ.ssRkn8xMgXjWElw2xeYQjVx6lFuesYwre9BFCQ8YFG4
